# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs Nantes tests"
  lane :test do
    scan(project: "Nantes/Nantes.xcodeproj", scheme: "Nantes", devices: ["iPhone 8"])
  end

  lane :lint do
    sh("brew list mint &>/dev/null || brew install mint")
    sh("mint run --mintfile ../Mintfile swiftlint swiftlint --path .. --strict --quiet")
  end
end
